/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_home_simplexmethod_SimplexMethodWrapper */

#ifndef _Included_com_home_simplexmethod_SimplexMethodWrapper
#define _Included_com_home_simplexmethod_SimplexMethodWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_home_simplexmethod_SimplexMethodWrapper
 * Method:    startWork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_home_simplexmethod_SimplexMethodWrapper_startWork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
